Revisions 08 11 21
borysigorevich/jokes pull request #1
Opened 2021-11-10 11:42 UTC by borysigorevich

2021-11-10 20:05 UTC, mike-gusiev requested changes

2021-11-10 20:05 UTC, mike-gusiev commented on README.md
>  The build is minified and the filenames include the hashes.\
1. треба щоб у тебе всюди були відступи однакові. зараз вони в тебе в різнобій ідуть: https://take.ms/1fQvj
2. коли наводиш мишкою на жарт - курс має змінюватися на руку. щоб показати що воно клікабельне
3. коли клікаєш на жарт - має відкриватися модальне вікно react bootstrap і змінюватися роут. щоб коли ти перегрузив сторінку - воно показало той самий жарт з модалкою
4. в мене видає помилку коли клікаю на якусь категорію https://take.ms/4ddsK
5. коли вибрав категорію і клікаєш на кнопку підгрузки - нічого не відбувається

2021-11-10 20:05 UTC, mike-gusiev commented on src/App.test.tsx
> +});
перед відправкою пул реквеста на рев'ю переглядай свій пул реквест. і виправиш все що помітиш самостійно, до того як мені відправляти на рев'ю.

якщо бачиш таку іконку, значить у цього файлу не вистачає переносу рядка в кінці.

2021-11-10 20:05 UTC, mike-gusiev commented on src/App.test.tsx
> +import React from 'react';
ствови папку src/tests. і туди поклади усі тести і снепшоти

2021-11-10 20:05 UTC, mike-gusiev commented on src/App.test.tsx
> +import EnzymeAdapter from '@wojtekmaj/enzyme-adapter-react-17'
крапки з комою інколи не ставиш. налаштуй на цьому проекті eslint, щоби воно тобі підсвічували усі неправильні відступи і забуті символи

2021-11-10 20:05 UTC, mike-gusiev commented on src/App.tsx
>  function App() {
використовуй коротку форму es6 функцій без return, там де це можливо

2021-11-10 20:05 UTC, mike-gusiev commented on src/components/joke/Joke.tsx
>      }, [params.id, dispatch])
ти не там помилки хендлиш. тобі треба ловити помилки в той момет, коли ти відправяєш ajax запити. і якщо ajax запит не пройшов - ти маєш діспатчити екшен з помилкою. який виключає лоадер і виводить попап з помилкою

2021-11-10 20:05 UTC, mike-gusiev commented on README.md
добав пліз ще лоадер, коли підгружаєш нову інформацію

2021-11-10 20:05 UTC, mike-gusiev commented on src/components/jokes/Jokes.tsx
> +                        {jokesState.categories.map((category: string, index) => <CustomNavLink as={Link}
ти виліз за ліміт в 120 символів. розбий переноси так, щоби усі вміщалося

2021-11-10 20:05 UTC, mike-gusiev commented on src/components/jokes/Jokes.tsx
> +                                <ListGroup.Item as={'li'} key={joke.id}
усі атрибути в яких не відбувається ніяких обчислень мають бути в html форматі - без скобок, з подвійними кавичками:
` <ListGroup.Item as="li"`

2021-11-10 20:05 UTC, mike-gusiev commented on src/redux/saga/jokesSaga.ts
>  import {put, takeEvery} from 'redux-saga/effects'
структура редаксу трохи неправильна. позбудься папок saga та store. і створи папку src/redux/ducks. і туди в окремі файли помісти усі екшени/редюсери/саги і тд одним файлом. все що відноситься до одного duck - має бути в одному файлі:
https://github.com/erikras/ducks-modular-redux

2021-11-10 20:05 UTC, mike-gusiev commented on src/redux/saga/jokesSaga.ts
> +const getJoke = async (id: undefined | string) => await axios.get('http://api.icndb.com/jokes/' + id)
повинось url в константи

2021-11-10 20:05 UTC, mike-gusiev commented on src/redux/saga/jokesSaga.ts
> +const getCategories = async () => await axios.get('http://api.icndb.com/categories')
axios не має бути в сагах. усе що відноситься до ajax запитів - повинось у файл src/api.js. а сюди імпорть тільки функції

2021-11-10 20:05 UTC, mike-gusiev commented on src/styled/Joke.ts
> +import styled from 'styled-components'
не зовсім зрозумів нащо цей файл

2021-11-10 20:05 UTC, mike-gusiev commented on src/components/joke/jokeStyles.ts
>  import styled from 'styled-components'
позбуться усіх styled components із папки src/components

2021-11-11 19:14 UTC, borysigorevich commented on README.md
>  The build is minified and the filenames include the hashes.\
4. в мене видає помилку коли клікаю на якусь категорію https://take.ms/4ddsK
--- это не ошибка, это значит что в этой категории нету шуток
5. коли вибрав категорію і клікаєш на кнопку підгрузки - нічого не відбувається
--- шутки подгружаются, только много шуток идут без категории и поэтому они будут отображаться в категории "all", если чуть дольше поклацать, то видно что в категориях "nerdy" & "explicit" начинают появляться шутки

2021-11-18 15:46 UTC, merged