Jest/enzyme
borysigorevich/jokes pull request #2
Opened 2021-11-15 17:50 UTC by borysigorevich

2021-11-16 07:56 UTC, mike-gusiev requested changes

2021-11-16 07:56 UTC, mike-gusiev commented on .idea/vcs.xml
> +</project>
добав в .gitignore усю папку .idea

2021-11-16 07:56 UTC, mike-gusiev commented on src/api.ts
> +import axios from "axios";
одинарні кавички мають бути

2021-11-16 07:56 UTC, mike-gusiev commented on src/App.tsx
> +export default App
крапка з комою

2021-11-16 07:56 UTC, mike-gusiev commented on src/App.tsx
> +)
крапка з комою

2021-11-16 07:56 UTC, mike-gusiev commented on src/api.ts
> +const randomJokesURL = 'http://api.icndb.com/jokes/random/'
крапка з комою

2021-11-16 07:56 UTC, mike-gusiev commented on src/api.ts
> +}
- крапка з комою
- не вистачає переносу рядка

2021-11-16 07:56 UTC, mike-gusiev commented on README.md
>  The build is minified and the filenames include the hashes.\
1) коли вибрав якусь категорію. і релоадиш сторінку - воно не показує жарти.
2) коли вибрана якась категорія - і клікаєш підгрузити нові жарти. нічого не відбувається

2021-11-16 07:56 UTC, mike-gusiev commented on src/styled/GlobalStyles.ts
> +        black: 'rgba(0,0,0,.9)'
став пробіли після коми

2021-11-16 07:56 UTC, mike-gusiev commented on src/styled/GlobalStyles.ts
> +        medium: '(max-width: 767px)'
створи файл для глобальних змінних styled components. і туди повиносили всі кольори і розміри в медіа запитах

2021-11-16 07:56 UTC, mike-gusiev commented on src/styled/GlobalStyles.ts
> +}
перенос рядка

2021-11-16 07:56 UTC, mike-gusiev commented on src/tests/Jokes.test.tsx
> +        const mockStore = {
ту частину тесту яка дубліється - винось в beforeAll або beforeEach

2021-11-16 07:56 UTC, mike-gusiev commented on src/tests/Jokes.test.tsx
> +    it('Three jokes after fetch', () => {
кожен тест має починатися зі слова should. і повинен читатися як
it should show 3 jokes after fetch

2021-11-16 07:56 UTC, mike-gusiev commented on src/tests/JokesTestVersion.tsx
> +const JokesTestVersion = ({jokesState, dispatch}: JokesProps) => {
а нашо в тестах ти створював компонент? чого не заімпортив існуючий?

2021-11-16 07:56 UTC, mike-gusiev commented on src/tests/joke-reducer.test.tsx
> +import {runSaga} from "redux-saga";
одинарні кавички

2021-11-16 11:08 UTC, borysigorevich commented on src/tests/JokesTestVersion.tsx
> +const JokesTestVersion = ({jokesState, dispatch}: JokesProps) => {
Не мог понять как пробросить mock store при использование useSelector & useDispatch.
Сейчас решил переписать подключение redux через connect и проблема решается

2021-11-18 08:01 UTC, mike-gusiev requested changes

2021-11-18 08:01 UTC, mike-gusiev commented on .gitignore
ці баги досі не пофікшені:
- коли вибрав якусь категорію. і релоадиш сторінку - воно не показує жарти.
- коли вибрана якась категорія - і клікаєш підгрузити нові жарти. нічого не відбувається

2021-11-18 08:01 UTC, mike-gusiev commented on src/api.ts
> +}
це теж не пофікшено

2021-11-18 08:01 UTC, mike-gusiev commented on src/components/joke/Joke.tsx
> +export default Joke;
переносу рядка не вистачає

2021-11-18 08:01 UTC, mike-gusiev commented on src/components/jokes/Jokes.tsx
> +import {actionsType} from "../../tests/Jokes.test";
налаштуй собі eslint на цьому проекті. щоб він підсвічував тобі де в тебе подвійні душки стоять. а де крапку с комою не стоять

2021-11-18 08:01 UTC, mike-gusiev commented on src/components/jokes/Jokes.tsx
> +    // const dispatch = useDispatch();
не можна зберігати в репозиторії закоментованний код. видали його звідси

2021-11-18 08:01 UTC, mike-gusiev commented on src/components/jokes/Jokes.tsx
> +        navigate('/')
крпки з комою

2021-11-18 08:01 UTC, mike-gusiev commented on src/components/jokes/Jokes.tsx
> +export default connect(mapStateToProps, mapDispatchToProps)(Jokes);
перенос рядка

2021-11-18 08:01 UTC, mike-gusiev commented on src/index.tsx
>  );
перенос рядка. ти чого не передивляєшся пул реквест перед тим як мені його скинути?

2021-11-18 08:01 UTC, mike-gusiev commented on src/redux/ducks/jokes.ts
> +import {SagaIterator} from "redux-saga";
подвійні кавички

2021-11-18 08:01 UTC, mike-gusiev commented on src/styled/GlobalStyles.ts
> +        medium: '(max-width: 767px)'
це теж не зробоено

2021-11-18 08:01 UTC, mike-gusiev commented on src/styled/GlobalStyles.ts
> +        black: 'rgba(0,0,0,.9)'
це теж не зробоено

2021-11-18 08:01 UTC, mike-gusiev commented on src/tests/Jokes.test.tsx
> +})
- перенос рядка
- крапка з комою в кінці кожного рядка пропустив

2021-11-18 08:01 UTC, mike-gusiev commented on src/tests/joke-reducer.test.tsx
> +import {mockState} from "./utils";
подвійні кавички

2021-11-18 15:46 UTC, merged